### ISSUE TITLE
fix(ui): docs pages crash on client-side navigation (path.join is not a function)

### ISSUE THREAD

**Issue by JSONbored** [JSONbored/loopover#7631]
## Summary

Every one of the ~48 `/docs/*` pages in `apps/loopover-ui` crashes with a full "This page didn't load" error screen when reached via normal in-app navigation (clicking a link) — direct hard page loads are fine, which is why this is easy to miss. Console shows:

```
TypeError: D.join is not a function
    at ... docs-source-*.js
    at Object.doc (...)
    at Object.docs (...)
```

## Root cause

`apps/loopover-ui/src/lib/docs-source.ts` imports `collections/server`, fumadocs-mdx's generated, filesystem-backed runtime module (globs every `content/docs/*.mdx` file, depends on Node's `path`). Every `docs.*.tsx` route's `loader()` imported it directly (`await import("@/lib/docs-source")`). TanStack Router route loaders run **both** on the server (SSR / hard loads) **and** in the browser (client-side / SPA navigations) — so on a soft navigation this server-only module executes in the browser, where `path.join` doesn't exist, and the route errors out.

This is a recent regression: introduced by #7607-adjacent work landing the fumadocs-mdx content pipeline migration (commit `5003fabe6`, 2026-07-16). Confirmed live on `loopover.ai` — clicking from the homepage into Docs, or between doc pages, breaks for real visitors.

## Fix

Move the fumadocs-mdx lookup behind a `createServerFn` (`docs-source.functions.ts`), matching this codebase's existing `.server.ts` + `createServerFn` pattern (see `config.server.ts` + `example.functions.ts`), so the lookup always runs server-side and the client fetches the result over the wire instead of re-executing the Node-only module in the browser. Updated all 48 `docs.*.tsx` route loaders.
